### ISSUE TITLE
Linux issue

### ISSUE THREAD

**Issue by dnaroid** [AnWeber/vscode-statusbar-command#1]
Please fix file names in imports:

import {Command} from './command';

import {CommandsController} from './commandsController';

Thanks

**Comment by AnWeber** [comment]
I don't know what is wrong with these file names. How should I fix the names?

Thanks for your help.

**Comment by dnaroid** [comment]
Files named as command.ts and commandsController.ts, but you import from 'Command' and  'CommandsController'. First letters in import...from must be a lower case. After renaming all works correctly.

**Comment by AnWeber** [comment]
Hello,

thanks for your pull request. Really wow. Sorry for the delay, but I needed a break from my fun coding projects. I will publish a new version in the next minutes

**Comment by dnaroid** [comment]
Hello, thanks for your nice project
