### ISSUE TITLE
Series of commands

### ISSUE THREAD

**Issue by ozum** [AnWeber/vscode-statusbar-command#10]
Hi,

Is it possible to add feature to execute series of commands. For example:

```json
    {
      "text": "$(fold)",
      "command": ["editor.foldAllBlockComments", "fold-imports.fold"],
      "tooltip": "Fold block comments and imports"
    },
```

**Comment by AnWeber** [comment]
Hi,

not directly. But you could use for example this [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-comma) and then configure the created multicommand in my extension.

**Comment by ozum** [comment]
Thanks that will do.
