### ISSUE TITLE
Make "command" property optional

### ISSUE THREAD

**Issue by moxwel** [AnWeber/vscode-statusbar-command#11]
I don't know if this is by design, a bug, or what, but I discover a _trick_.

If I put `text: " "` and **no command** on the Statusbar Commands, like this:
```json
{"text": " ","priority": 1,"alignment": "left"}
```
It makes a "spacer".

---

For example:
```json
{
  "text": "$(terminal)",
  "alignment": "left",
  "command": "workbench.action.terminal.toggleTerminal",
  "priority": 10030,
},
{"text": " ","priority": 10011,"alignment": "left"},
{
  "text": "$(file-binary) Hex",
  "alignment": "left",
  "command": "hexEditor.openFile",
  "priority": 10007,
},
```
That code makes a space between the two commands:
![image](https://user-images.githubusercontent.com/49621788/118331850-2e23d280-b4d7-11eb-8a31-a3795e68d969.png)

**I think it's very neat**, but in `settings.json`, there's a warning:

![image](https://user-images.githubusercontent.com/49621788/118332041-76db8b80-b4d7-11eb-9519-c3e0ebc5bfd1.png)

I'm wondering if that "command" property can be _optional_? So, these warnings doesn't appear. Anyway, It's just a esthetic detail.

**Comment by AnWeber** [comment]
I released a update. Could you please test. Thanks

**Comment by moxwel** [comment]
Hmm, I just updated, and the warning is still there.

![image](https://user-images.githubusercontent.com/49621788/118335051-c5d7ef80-b4dc-11eb-876c-b21ddd0fad54.png)

**Comment by AnWeber** [comment]
Yes, you are right. That fixed it. Yesterday I did not test and edited the package.json in the browser. Now it works, tested. A nice feature by the way.

**Comment by moxwel** [comment]
Nice!
