### ISSUE TITLE
Explanation of Recent Enhancement per v1.7.0

### ISSUE THREAD

**Issue by SolarTheory** [AnWeber/vscode-statusbar-command#13]
Changelog for v1.7.0 says "support id and name of StatusbarItem".  What does this mean?  I can't find any explanation on how this new feature can be used in a practical sense.  So, I guess I can now include the object keys/properties "ID" and "Name" for each statusbar item? What is the purpose of these additional properties and how to use?  

Sorry if this is documented already somewhere but I can't figure out how I can use this new feature.

Thanks!

**Comment by AnWeber** [comment]
Sorry, my documentation is always rather short. The properties were introduced by VSCode with version 1.57.0. [Here](https://code.visualstudio.com/updates/v1_57#_status-bar-item-id-and-name-properties) is the description.

**Comment by AnWeber** [comment]
Example in readme.md with Id and Name
```json
[
    {
      "text": "$(gear)",
      "tooltip": "workspace settings",
      "id": "settings",
      "name": "settings",
      "priority": -1000,
      "alignment": "right",
      "command": "workbench.action.openWorkspaceSettings"
    },
    {
        "text": "$(file-text)",
        "id": "format",
        "name": "formatDocument",
        "tooltip": "format",
        "alignment": "left",
        "priority": 100,
        "include": "\\.js",
        "command": "editor.action.formatDocument"
    },
    {
      "text": "TS",
      "tooltip": "Typescript Server neustarten",
      "alignment": "right",
      "priority": 1000,
      "id": "ts2",
      "name": "Typescript Server neustarten",
      "include": "\\.[ts|vue]",
      "command": "typescript.restartTsServer"
    },
    {
      "text": "$(terminal)",
      "tooltip": "Terminal",
      "id": "Terminal",
      "name": "Terminal",
      "alignment": "right",
      "priority": 1000,
      "command": "workbench.action.terminal.toggleTerminal"
    },{
        "text": "ctrl+h",
        "id": "runTask",
        "name": "runTask",
        "command": "workbench.action.tasks.runTask",
        "arguments": ["taskName"]
    }
  ],
```
StatusBar Items are added independently to menu
![image](https://user-images.githubusercontent.com/13434739/121845270-7b1ce380-cce5-11eb-89b4-bc5cbf6e86ae.png)

**Comment by SolarTheory** [comment]
Hey, thanks so much for the additional info.  I was not aware of the new properties introduced by v1.57.0.  I'll look into it.

Great extension by the way!

**Comment by AnWeber** [comment]
thanks
