### ISSUE TITLE
Option to remove the default gear icon

### ISSUE THREAD

**Issue by Signum21** [AnWeber/vscode-statusbar-command#14]
Can you add an option to remove the default gear icon in the status bar?
<img width="149" alt="Immagine 2021-07-28 155501" src="https://user-images.githubusercontent.com/22285224/127334659-d904fa5f-c862-403f-8b46-7e387792eea1.png">

**Comment by AnWeber** [comment]
You just have to set an empty array for the setting `statusbar_command.commands` . This would overwrite the default, however I will simply leave the default empty with the next version.
