### ISSUE TITLE
Add an optional property for "RegExp flags" when using "filter..."

### ISSUE THREAD

**Issue by DuckyMomo20012** [AnWeber/vscode-statusbar-command#16]
Can you add more regexp flags such as "g, m..." when using the "filter" property, instead of the 'u' flag? (I found it in file statusBarCommand.ts, line 142).
Reason: I add a button to open the file under the cursor using the extension: "Open file" (Frank Stuetzer) and I only want to show that one when it matches relative/absolute path regex using "filterText", but I still can't find a way to workarounds it. Therefore, adding more flags might help me and others a lot.

**Comment by AnWeber** [comment]
I have now added optional flags. Can you please test it.

**Comment by DuckyMomo20012** [comment]
Thank you for your quick response. I reinstalled the extension and tested it and it worked like a charm. I also tested it with combined flags such as "gm" or "gmi".

**Comment by AnWeber** [comment]
Thanks for testing.
