### ISSUE TITLE
[Feature Request] Run external command directly

### ISSUE THREAD

**Issue by lonix1** [AnWeber/vscode-statusbar-command#17]
It would be nice to be able to run an external command, like so:

Linux:
````json
"command": "gnome-terminal --working-directory=$(pwd)/src/Foo/ --quiet --command 'ls -lah'",
````
Windows:
````json
"command": "cmd ...etc.",
````

That opens the command directly, without going through the built-in terminal, or a companion extension.

As you can see in [this extension](https://marketplace.visualstudio.com/items?itemName=gsppvo.vscode-commandbar), it's possible - but that extension is abandonware.

Would be nice to have that functionality in this extension. Thanks!

**Comment by AnWeber** [comment]
Only as a supplement. It is also implementable with standard VS code functions.

* add task.json with task
```
{
	"label": "test",
	"type": "shell",
	"command": "notepad.exe"
}
```
* add statusbar command
```
{
        "text": "test",
        "id": "runTask",
        "name": "runTask",
        "command": "workbench.action.tasks.runTask",
        "arguments": ["test"]
    }
```
