### ISSUE TITLE
Ignore INCLUDE at startup

### ISSUE THREAD

**Issue by danilort** [AnWeber/vscode-statusbar-command#19]
# Description of the problem

For a few weeks there is a problem, which I had not had before
Each time I open a project, **all the elements** of the status bar are shown:

![immagine](https://user-images.githubusercontent.com/16148184/147919519-b2130654-5dfa-4ade-a7db-1ec1c0310d3a.png)

Later, when selecting a different file, it shows only the necessary elements:

![immagine](https://user-images.githubusercontent.com/16148184/147919545-13c3020c-6794-49dc-a3ae-5d6353bbb667.png)
![immagine](https://user-images.githubusercontent.com/16148184/147919550-9c118824-044e-45d7-8eb0-910e3bd70776.png)
![immagine](https://user-images.githubusercontent.com/16148184/147919553-ca8ac21b-d13f-4342-ba17-f82d6f55bcf5.png)

The problem occurs when I open any project, or a single file.
The problem occurs even if disabled all extensions, except "statusBarcommand" and "Italian Language Pack for VSCODE".

# Information

StatusBarCommand v2.2.0

### VSCODE

- Versione: 1.63.2
- Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
- Data: 2021-12-15T09:40:02.816Z
- Electron: 13.5.2
- Chromium: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- Sistema operativo: Windows_NT x64 10.0.19042

### Settings

```
"statusbar_command.commands": 
    [
        //DBML
        {
            "text"     : "DBML->SQL",
            "tooltip"  : "Esporta da DBML a SQL",
            "alignment": "left",
            "priority" : 1,
            "include"  : "(.dbml)",
            "command"  : "vscode-dbml.export"
        },
        {
            "text"     : "SQL->DBML",
            "tooltip"  : "Esporta da SQL a DBML",
            "alignment": "left",
            "priority" : 1,
            "include"  : "(.sql)",
            "command"  : "vscode-dbml.import",
            "arguments": [""]
        },
        //MONKEY-C
        {
            "text"     : "MONKEY",
            "tooltip"  : "Elenco comandi per MonkeyC",
            "alignment": "left",
            "priority" : 1,
            "include"  : "(.mc|manifest.xml)",
            "command"  : "workbench.action.quickOpen",
            "arguments": [">Monkey "]
        },
        {
            "text"     : "$(question)",
            "tooltip"  : "Documentazione",
            "alignment": "left",
            "priority" : 1,
            "include"  : "(.mc|manifest.xml)",
            "command"  : "monkeyc.viewDocumentation"
        },
        {
            "text"     : "$(triangle-right)",
            "tooltip"  : "Esegui",
            "alignment": "left",
            "priority" : 1,
            "include"  : "(.mc|manifest.xml)",
            "command"  : "monkeyc.runProgram"
        },
        // SPLIT IN GROUP
        {
            "text"     : "$(split-vertical)",
            "color"    : "#FFFF00",
            "tooltip"  : "Attiva lo Split in Group",
            "alignment": "left",
            "priority" : 2,
            "command"  : "workbench.action.toggleSplitEditorInGroup"
        },
    ],
```

**Comment by AnWeber** [comment]
It seems the following [commit of mine is to blame](https://github.com/AnWeber/vscode-statusbar-command/commit/c07875d075130beacb0e9f05aac21971bafe19c7). I have removed the call to Refresh when initializing. I will have a look at what was the reason here. But probably it was rather not intentional.

**Comment by danilort** [comment]
I performed other tests with your .vsix files:

- v1.10.0 works well
- v.2.0.0 works well
- v.2.1.0 works well
- v.2.2.0 presents the problem

**Comment by AnWeber** [comment]
I just deployed an update v2.2.1 by fixing the bug. Would you like to test it too please. Thank you.

**Comment by danilort** [comment]
V2.2.1 is ok!
Thank you for your work and good 2022!

**Comment by AnWeber** [comment]
Happy New Year to you too. Good luck and stay healthy:-)
