### ISSUE TITLE
Statusbar is not giving back the keyboard focus to the editor

### ISSUE THREAD

**Issue by Z-E-D** [AnWeber/vscode-statusbar-command#20]
There are some commands that are not giving back the focus to the editor like these:
- "Save",
- "Toggle Line Comment" / "Toggle Block Comment",
- "Go to Bracket",
- "Go to Parent Fold" / "Go to Previous/Next Folding Range",
- "Go to Definition",
- "Go to Previous/Next Symbol Highlight",
- "Toggle Full Screen",
- "Toggle Split Editor in Group Layout",
- ...

On other side, there are some commands that are not stealing the focus from editor, like these:
- "Undo" / "Redo",
- "Go Back" / "Go Forward",
- "Go to Last Edit Location",
- "Toggle Split Editor in Group",
- ...

For example, if I type any text in editor and press Ctrl+S or choose the File / Save menu item, the focus will remain in the editor, but not if I click on the Statusbar button with the same command. However, the Statusbar button for e.g. "Undo" will leave the focus to the editor.

I tried unsucesfully to give the focus back to the editor, e.g. for "Go to Next Symbol Highlight", with this:
`"command": "editor.action.wordHighlight.next; workbench.action.focusActiveEditorGroup"`

and with this:
```
"scriptEvents": ["vscode.window.onDidChangeActiveTextEditor", "vscode.workspace.onDidChangeTextDocument"],
"script": "editor.action.wordHighlight.next; workbench.action.focusActiveEditorGroup;"
```

At first I though that commands beginning with the "editor.action" are not giving back the focus to the editor, unlike those with the "workbench.action" on the beginning. However, that is not always the case, e.g. the "Save" command is "workbench.action.files.save" and it is not giving back the focus.

I suggest that your extension check out if the editor is active before its execution, and if it is to give back the focus to it after the execution. Or, at least make that optional.

**Comment by AnWeber** [comment]
I think there is a misunderstanding of what the script does. The script is not executed at the time of the command, but when the ScriptsEvents occur. If StatusBarItem is pressed, no code is executed by me but the corresponding command  is started directly from VSCode. Therefore it is not possible for me to change the focus or to correct it afterwards. It would be possible to register a custom javascript as a command, but I have intentionally not done this so far. There are already several other solutions and you should not build everything twice.
Probably it would be better to put an issue in [VSCode repo](https://github.com/microsoft/vscode/issues) or ask a question in  https://stackoverflow.com/questions/tagged/visual-studio-code, how to solve the problem. I already had a similar problem (https://github.com/microsoft/vscode/issues/12214) once where a solution was found.

**Comment by Z-E-D** [comment]
>It would be possible to register a custom javascript as a command, but I have intentionally not done this so far.

I am sorry, but I am not sure that understand your explanation. Haven't you already added a possibility to register a custom javascript as a command with these recently added "scriptEvents" and "script" settings?

I am just trying to add the "workbench.action.focusActiveEditorGroup;", which I suppose would give the focus back to the editor, after the wanted command. However, I am not sure that my 
trying with the "scriptEvents" and "script" could work at all, because it would be executed only on those specified events, but not when I click the Statusbar button.

If the existing "command" setting accepts more than one VSCode command, then I could add the mentioned command to the end of "command" and it would be executed exactly when the Status bar is clicked.

If you don't want to change the behavior of the existing "command" settings, maybe you could e.g. modify the extension to execute the user specified javascript in the "script" settings when the Statusbar button is clicked, if the "scriptEvents" settings is leaved empty/unspecified for that particular item.

By the way, if I read the source code of your extension correctly, I think that you should mention somewhere in the documentation that "scriptEvents" and "script" are applied only when no other filter settings are included like "filterLanguageId" or "filterFileName".

**Comment by Z-E-D** [comment]
I just found the way how to accomplish what I wanted with the help of the [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command)
extension. For example:
```
    "statusbar_command.commands": [
        {
            "text": "$(save)",
            "id": "sbc_saveWithoutFormatting",
            "name": "Save Without Formatting",
            "tooltip": "Save Without Formatting (Ctrl+K Ctrl+Shift+S)",
            "priority": -100,
            "alignment": "left",
            "command": "multiCommand.saveWithoutFormatting"
        }
    ],
    "multiCommand.commands": [
        {
            "command": "multiCommand.saveWithoutFormatting",
            "sequence": [
                "workbench.action.files.saveWithoutFormatting",
                "workbench.action.focusActiveEditorGroup"
            ]
        }
    ]

```

It requires some more typing and it would be great if you incorporate something similar into your extension, but the problem is solved anyway.

**Comment by AnWeber** [comment]
@Z-E-D  Cool that you found a solution:-) I have also considered expanding the functions at one point. But I decided against it, because there are exactly already other extension for this use case. I can't do better than these developers. I represent the Unix philosophy. Do a thing and do it well.
