### ISSUE TITLE
not wroking in vscode version 1.79.0

### ISSUE THREAD

**Issue by seb4nihel** [AnWeber/vscode-statusbar-command#27]
As of vscode Version 1.79.0 all my commands are gone, did someone noticed this as well?

extension version: v2.7.0

vscode:

Version: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:28:32.941Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux arm64 6.3.0-asahi-7-1-edge-ARCH

**Comment by AnWeber** [comment]
@seb4nihel will check it.

**Comment by AnWeber** [comment]
@seb4nihel It still works correctly for me. My configured buttons also appear with VSCode 1.79.0 on Windows.

<img width="311" alt="image" src="https://github.com/AnWeber/vscode-statusbar-command/assets/13434739/cffaf0cf-d01a-4f31-b027-bab255de9981">

**Comment by seb4nihel** [comment]
@AnWeber I resolved the issue, i had several buttons with the same id in the json config. This malformed settings worked for some time but stopped working now. I noticed it, fixed it and the statusbar commands worked again.
So issue solved! Thank you very much for quick response and confirmation!
