### ISSUE TITLE
Can't run command in terminal

### ISSUE THREAD

**Issue by BachiMjavanadze** [AnWeber/vscode-statusbar-command#32]
I want to run python current script in `Git Bash` terminal, so my settings are:

```
 "statusbar_command.commands": [
    {
      "text": "$(play)",
      "id": "RunPython",
      "name": "RunPython",
      "tooltip": "RunPython",
     "command": "workbench.action.tasks.runTask",
      "arguments": [
        "clear; python ${relativeFile}",
      ]
    },
]
```

but it does not work. 

I've try different version:

```
{
      "text": "$(play)",
      "id": "RunPython",
      "name": "RunPython,
      "tooltip": "RunPython",
      "command": "workbench.action.terminal.sendSequence",
      "arguments": [
        "clear; python ${relativeFile}"
     ]
}
```
but it does not work. too.

but this command works correctly:

```
{
  "text": "$(play)",
  "id": "RunServer",
  "name": "runTask",
  "tooltip": "ng serve",
  "command": "workbench.action.tasks.runTask",
  "arguments": [
    "npm: start"
  ]
},
```

what is my mistake?

**Comment by AnWeber** [comment]
What is the Input of the runTask command? I thought it is the name of the task.

**Comment by BachiMjavanadze** [comment]
> What is the Input of the runTask command? 

I don't want to specify any name at runtime. "RunServer" in the case of "Angular" works without passing any data to the input, I just click the "Run" button and that's it.

**Comment by AnWeber** [comment]
@BachiMjavanadze  you need to use the name of your task as arguments is `clear; python ${relativeFile}` really your task name?

**Comment by BachiMjavanadze** [comment]
> @BachiMjavanadze you need to use the name of your task as arguments is `clear; python ${relativeFile}` really your task name?

I got you. no, that's not the name of my task. I just need to run a simple terminal command. Isn't this possible?

**Comment by AnWeber** [comment]
This command from Microsoft does Not provide this Feature. You need to create a task and code your cli command there. After that you can reference this task in my extension.

**Comment by AnWeber** [comment]
@BachiMjavanadze I found an extension which is capable of running shell commands. Maybe you are interested https://github.com/petekinnecom/terminal-command-keys
