### ISSUE TITLE
editor.action.commentLine no longer working in VSCode v1.5.1

### ISSUE THREAD

**Issue by jgolieb** [AnWeber/vscode-statusbar-command#4]
The statusbar command button defined as follows has stopped working after upgrading to VSCode v.1.5.1:

```
"statusbar_command.commands": [
        {
            "text": "//",
            "tooltip": "Toggle Comment",
            "alignment": "left",
            "command": "editor.action.commentLine"
        }
    ]
```

This was working fine before (v1.4) but now I get the error "Command 'Toggle Line Comment' can not be run from here."  The command editor.action.commentLine still works fine using the default key binding (ctrl + /) or from the command palette.

**Comment by AnWeber** [comment]
vscode 1.5.2 does not fix the issue. I think it is an issue directly in vs code. This extension uses the API [createStatusbarItem](https://code.visualstudio.com/docs/extensionAPI/vscode-api). Then the statusbarItem property command is set. When clicking on the button, no code of my extension is executed. The extension only manages the creation und destruction of the buttons.

**Comment by AnWeber** [comment]
I created a new issue in [vscode repo] (https://github.com/Microsoft/vscode/issues/12214).

**Comment by AnWeber** [comment]
this issue was fixed by microsoft. In one of the next releases this feature works again. thanks.
