### ISSUE TITLE
Command 'Save All' does not work

### ISSUE THREAD

**Issue by JM2014** [AnWeber/vscode-statusbar-command#5]
Hello, 

I tried under Visual Studio Code 1.7.1 (LInux) the following-settings:

"statusbar_command.commands": [{
        "text": "Save All",
        "tooltip": "SaveAll",
        "alignment": "left",
        "command": "workbench.action.files.saveAll"
    }] 

but get the error message: 
"Command 'Save All' can not be run from here."

Does anybody have an idea to solve it or has a workaround?

Greetings
Juergen

**Comment by AnWeber** [comment]
Hi,

thanks for your report. It seems this isssue is an error directly in vscode. I created an issue in the repository.
https://github.com/Microsoft/vscode/issues/15059

**Comment by AnWeber** [comment]
I closed the issue in the vs code repo. The message only appears, if you have no dirty files. If you dislike this behavior, please open an issue in the vs code repo.

**Comment by JM2014** [comment]
I did not realize that it happens only, if there is nothing to save. 
@AnWeber: Thankyou for your quick action and answer. For me it is fine....
