### ISSUE TITLE
Support for custom tasks

### ISSUE THREAD

**Issue by romancow** [AnWeber/vscode-statusbar-command#6]
Love the extension, but I'd really love a way to define status bar commands for my custom tasks (e.g. ones other than `workbench.action.tasks.test` and `workbench.action.tasks.build`). I know Microsoft just added support for task key bindings that looks like this:
```json
{
    "key": "ctrl+h",
    "command": "workbench.action.tasks.runTask",
    "args": "taskName"
}
```

Would it be possible to do something like this with the statusbar-commands extension?

**Comment by AnWeber** [comment]
Thanks for your support. At the moment the provided api of vscode does not allow this feature. I created a [issue 22353](https://github.com/Microsoft/vscode/issues/22353) in the repository to request this feature.

**Comment by fabiospampinato** [comment]
@AnWeber It's actually already possible to pass arbitrary arguments to commands, it just requires some tinkering. My [Commands](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands) extension supports it.

**Comment by AnWeber** [comment]
@fabiospampinato thanks. I will add your idea with this proxy command to my extension

**Comment by AnWeber** [comment]
finally:-) sorry,
